// server/models/Contract.js

const mongoose = require('mongoose');

const ContractSchema = new mongoose.Schema({
    
    
    filename: { // The unique filename generated by Multer (e.g., contract-1719468800000-123456789.pdf)
        type: String,
        required: true,
        unique: true
    },
    originalname: { // The original name of the file uploaded by the user (e.g., MyImportantAgreement.pdf)
        type: String,
        required: true
    },
    mimetype: { // MIME type of the file (e.g., application/pdf)
        type: String,
        required: true
    },
    size: { // Size of the file in bytes
        type: Number,
        required: true
    },
    path: { // Full path to the file on the server (Multer's destination + filename)
        type: String,
        required: true
    },
    extractedText: { // The full text extracted from the PDF
        type: String,
        required: true
    },
    uploadDate: { // Timestamp of when the contract was uploaded
        type: Date,
        default: Date.now
    }
});

// Create the Mongoose model
const Contract = mongoose.model('Contract', ContractSchema);

module.exports = Contract;
